version: '3.3'
services:
  streamingdb:
    container_name: streamingdb
    restart: always
    image: streamingdb
    build:
      context: ./db
    volumes:
      - streamingdb:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 6432:6432
    expose:
      - 6432

  streaminggraphql:
    container_name: streaminggraphql
    restart: always
    image: streaminggraphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - streamingdb
    networks:
      - network
    ports:
      - 6433:6433
    expose:
      - 6433

networks:
  network:

volumes:
  streamingdb:
